services:
  api:
    container_name: triage_web
    build: ./back-end
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      MONGODB_URI: mongodb+srv://juanesmontoya92:tdea@electiva2.zd1g5.mongodb.net/triageDb
      JWT_SECRET: anysecret
    volumes:
      - .:/app
    depends_on:
      - mongo_db

  mongo_db:
    container_name: triage_web-mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  
  frontend:
    container_name: triage_web-frontend
    build: ./Frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - api

volumes:
  mongo_data: {}