services:
  api:
    container_name: backend
    build: 
      context: ./back-end
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      MONGODB_URI: mongodb+srv://juanesmontoya92:tdea@electiva2.zd1g5.mongodb.net/triageDb
      JWT_SECRET: anysecret
      PYTHON_URL: http://python:3002/processData
      NODE_ENV: development
    volumes:
      - ./back-end:/app
    depends_on:
      - mongo_db
      - python
    networks:
      - triage-network

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  
  frontend:
    container_name: frontend
    build: 
      context: ./Frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://localhost:3000/
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

  python:
    container_name: python
    build: 
      context: ./python
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3002:3002"
    environment:
      MONGODB_URI: mongodb+srv://juanesmontoya92:tdea@electiva2.zd1g5.mongodb.net/triageDb
    volumes:
      - ./python:/app
      - /app/venv
    networks:
      - triage-network

volumes:
  mongo_data: {}

networks:
  triage-network:
    driver: bridge