services:
  api:
    container_name: backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      MONGODB_URI: mongodb+srv://juanesmontoya92:tdea@electiva2.zd1g5.mongodb.net/triageDb
      JWT_SECRET: anysecret
      PYTHON_URL: http://python:3002/processData
    depends_on:
      - python
      - mongo_db
    networks:
      - triage-network

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - triage-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL="http://api:3000"
    ports:
      - "8080:80" # Producción servida por Nginx
    depends_on:
      - api
    networks:
      - triage-network

  python:
    container_name: python
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - triage-network

volumes:
  mongo_data: {}

networks:
  triage-network:
    driver: bridge
