services:
  api:
    container_name: triage_web
    build: 
      context: ./back-end
    command: npm start
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      MONGODB_URI: mongodb+srv://juanesmontoya92:tdea@electiva2.zd1g5.mongodb.net/triageDb
      JWT_SECRET: anysecret
      PYTHON_URL: http://python:3002/processData
    volumes:
      - ./back-end:/app
    depends_on:
      - mongo_db

  mongo_db:
    container_name: triage_web-mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  
  frontend:
    container_name: triage_web-frontend
    build: 
      context: ./Frontend
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

  python:
    container_name: triage_web-python
    build: 
      context: ./python
    working_dir: /app
    ports:
      - "3002:3002"
    environment:
      MONGODB_URI: mongodb+srv://juanesmontoya92:tdea@electiva2.zd1g5.mongodb.net/triageDb
    volumes:
      - ./python:/app
      - /app/venv
    depends_on:
      - api

volumes:
  mongo_data: {}